data:
  transcript_path: data/transcript_clean.csv
  audio_dir: data/wav_clean
  text_column: Transcript
  filename_column: SentenceID
  sample_rate: 16000
  seed: 42

model:
  pretrained_name: cahya/wav2vec2-large-xlsr-javanese

training:
  batch_size: 8
  learning_rate: 0.00001
  weight_decay: 0.00001
  epochs: 10
  gradient_accumulation_steps: 2
  logging_steps: 50
  save_dir: checkpoints/finetune
  warmup_ratio: 0.1
  min_duration_seconds: 0.5
